### PR TITLE
Include missing ISO codes mapping

### PR DESCRIPTION
**Pull request by andrebonna**
Including:
- Bonaire, Sint Eustatius and Sab (BES -> BQ)
- Curaçao (CUW -> CW)
- Sint Maarten (Dutch part) (SXM -> SX)

### CODE REVIEW

**Comment by msirghi** [comment]
Hi, is there any way this can be merged?

**Comment by klzns** [comment]
@igorbrasileiro @victorhmp

**Comment by msirghi** [comment]
@victorhmp, is there any way to merge it?

**Comment by Maryia-Zharykava** [comment]
Hello guys!
Could you please merge this changes? We are currently facing issue with SXM country (Sint Maarten (Dutch part))?

**Pull request merged**
